export const FETCH_TEAS_START = 'FETCH_TEAS_START';
export const FETCH_TEAS_SUCCESS = 'LOADING_TEAS_SUCCESS';
export const FETCH_TEAS_FAIL = 'FETCH_TEAS_FAIL';
export const FETCH_MORE_TEAS = 'FETCH_MORE_TEAS';

export const CREATE_TEA_START = 'CREATE_TEA_START';
export const CREATE_TEA_SUCCESS = 'CREATE_TEA_SUCCESS';
export const CREATE_TEA_ERROR = 'CREATE_TEA_ERROR';

export const BLOCKED_IP = 'BLOCKED_IP';

export const FETCH_TEA_START = 'FETCH_TEA_START';
export const FETCH_TEA_SUCCESS = 'FETCH_TEA_SUCCESS';
export const FETCH_TEA_FAIL = 'FETCH_TEA_FAIL';

export const CREATE_COMMENT_START = 'CREATE_COMMENT_START';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL';

export const LOAD_FAKE_TEA = 'LOAD_FAKE_TEA';
export const LOAD_FAKE_COMMENT = 'LOAD_FAKE_COMMENT';

export const UPDATE_VOTE = 'UPDATE_VOTE';